FROM python:3

WORKDIR /app

COPY ./requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

# Could omit files with a .dockerignore instead
COPY . .

# TODO: Wait for postgres
ENTRYPOINT \
    echo "Postgres is up - executing command";

CMD [ "gunicorn", "--bind=0.0.0.0:8000", "src.wsgi" ]